#! python3
# 2048Bot.py - Python Script to automatically play out 2048

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

browser = webdriver.Firefox()
browser.get('https://gabrielecirulli.github.io/2048/')
html_elem = browser.find_element_by_class_name('grid-container')
html_elem.click()

while True:
    html_elem.send_keys(Keys.ARROW_UP)
    html_elem.send_keys(Keys.ARROW_RIGHT)
    html_elem.send_keys(Keys.ARROW_DOWN)
    html_elem.send_keys(Keys.ARROW_LEFT)